name: codenest
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # TOTP and state management
  crypto: ^3.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.0.0

  # App icon generation
  flutter_launcher_icons: ^0.13.1
# Firebase dependencies
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/images/
  fonts:
  - family: NotoSans
    fonts:
      - asset: "assets/fonts/NotoSans-VariableFont_wdth,wght.ttf"
      - asset: "assets/fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf"
      - asset: "assets/fonts/NotoSans-Light.ttf"
  - family: NotoSansMono
    fonts:
      - asset: "assets/fonts/NotoSansMono-VariableFont_wdth,wght.ttf"
        style: italic

