// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07joMNCxaEQ7WmsnTc6oPetaJvF8Qbyg',
    appId: '1:101599613786:web:ea3873cfea05a2eff21963',
    messagingSenderId: '101599613786',
    projectId: 'codenestauthapp',
    authDomain: 'codenestauthapp.firebaseapp.com',
    storageBucket: 'codenestauthapp.firebasestorage.app',
    measurementId: 'G-M25TFXKM5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4J-RNeDV_CPidbhgnRxWgEcuTg2Y8hyI',
    appId: '1:101599613786:android:2fdbe088669fdc4ff21963',
    messagingSenderId: '101599613786',
    projectId: 'codenestauthapp',
    storageBucket: 'codenestauthapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFGFEpoeWAcn1kNBStboFQQM181WvjwXM',
    appId: '1:101599613786:ios:e0d99f9cb669a597f21963',
    messagingSenderId: '101599613786',
    projectId: 'codenestauthapp',
    storageBucket: 'codenestauthapp.firebasestorage.app',
    iosClientId: '101599613786-986hpka9fukktqqo9lpkai7q188qhkhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTotp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFGFEpoeWAcn1kNBStboFQQM181WvjwXM',
    appId: '1:101599613786:ios:e0d99f9cb669a597f21963',
    messagingSenderId: '101599613786',
    projectId: 'codenestauthapp',
    storageBucket: 'codenestauthapp.firebasestorage.app',
    iosClientId: '101599613786-986hpka9fukktqqo9lpkai7q188qhkhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTotp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA07joMNCxaEQ7WmsnTc6oPetaJvF8Qbyg',
    appId: '1:101599613786:web:d196086cdb18b3e8f21963',
    messagingSenderId: '101599613786',
    projectId: 'codenestauthapp',
    authDomain: 'codenestauthapp.firebaseapp.com',
    storageBucket: 'codenestauthapp.firebasestorage.app',
    measurementId: 'G-3VV4X1E1RL',
  );
}
